### ISSUE TITLE
Cannot disable or uninstall

### ISSUE THREAD

**Issue by xdtj777** [iCharlesZ/vscode-live2d-models#1]
Hi, I really like the idea of this plugin.
The problem is the plugin cannot be uninstalled or disabled. It stays there even when uninstalled and reloaded.
I have to fully reinstall VSCode to remove it.

**Comment by iCharlesZ** [comment]
This is the live2d model. Do you mean how to uninstall vscode extension?
https://github.com/iCharlesZ/vscode-live2d#install-and-uninstall-%E5%AE%89%E8%A3%85%E4%B8%8E%E5%8D%B8%E8%BD%BD

> If you have node.js installed, After the extension is deleted, the live2d style will be deleted automatically.
If node.js is not installed, Need to set {"vscode-live2d.enabled": false} in settings.json, then delete the extension.
Or you can directly click on the extension in the activity bar on the left, Find vscode-live2d, Click the settings button in the lower right corner of vscode-live2d, select extension settings, Then uncheck "vscode-live2d.enabled", Finally delete the extension.
